### PR TITLE
Small usability enhancements. New shortcode arguments. Post list table now shows Category column and default ordering by descending post date.

### PR DESCRIPTION
**Pull request by darrenkearney**
This pull request adds the ability for a person to further customize the operation of Related Posts For Wordpress within their posts by adding some extra love to the shortcode.

### [rp4wp class="" ] ###
You can now add custom CSS class(es) to the output's parent element. This allows multiple styles for related posts instead of just one, simply define it in the shortcode.
```html
[rp4wp] <!-- default style -->
[rp4wp class="my-additional-css-style"] <!-- additional css class allows additional styles -->
[rp4wp class="my-additional-css-style float-right"] <!-- can have multiple classes in one -->
```

### [rp4wp offset=0 ] ###
You can now add an offset to the shortcode. It's zero based, so `offset=0` (or no offset) would return a list of posts starting from the first post. `offset=1` would start from the second post and so on. It only returns linked posts from that offset onwards and does not around to the beginning to fill out the number of posts specified in the plugin settings. If combined with 'limit' you can easily have multiple shortcodes on a page that show different slices of your linked posts.
```html
[rp4wp offset=1] <!-- starts displaying linked posts from second post -->
[rp4wp limit=2] <!-- displays the first two linked posts -->
[rp4wp limit=2 offset=2] <!-- displays the second two linked posts (assuming at least 4 linked posts) -->
```

Together these enhancements can get multiple occurances of the related posts shortcode output on a page without displaying duplicate posts, with each occurrence given extra styles you can really customize the appearance. It requires some manual control and your own css styles, but I think it adds something nice to this plugin.
```html
[rp4wp limit=2] <!-- the first set of linked posts, default style -->
[rp4wp limit=2 offset=2" class="dark-style"] <!-- the second linked posts, in alternate style -->
```

### CODE REVIEW

**Comment by barrykooij** [comment]
Sorry for my late response, missed this for some reason. Added to 2.1.0 milestone

**Comment by darrenkearney** [comment]
Just added a simple adjustment that makes the plugin a bit easier to use for a medium sized site with thousands of posts.

**Comment by KZeni** [comment]
How/why has this been hanging around for so many years with it not having any question/opposition while not being adopted? Just wondering about the activity/support of this plugin (especially when there's a paid option being considered for this.)

**Comment by darrenkearney** [comment]
@KZeni Hello Kurt,

I had a quick look at the readme and it seems the main branch latest version is v2.0.3.

Barry stated that my PR would be considered for the next major version milestone, but it seems this project has not been updated much since I made this pull request on 30th November 2017.

I haven't reviewed my PR since I wrote it three years ago and I'm dreading the sight of it!

Perhaps if you find my contribution useful you can pull a copy from my fork for your own needs. Please note I will likely not contribute further to this.

I will close my old pull request. It's been open long enough!

Have a nice weekend! 

Best,
Darren

**Pull request closed without merging**
